# Generated by Django 5.2.6 on 2025-10-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Mashina egasi'), ('renter', 'Ijara oluvchi')], max_length=10),
        ),
    ]
