# Generated by Django 5.2.6 on 2025-10-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('inactive', 'Faol emas'), ('available', 'Mavjud'), ('rented', 'Ijaraga berilgan'), ('maintenance', "Ta'mirda")], default='inactive', max_length=20),
        ),
    ]
