# Generated by Django 5.2.4 on 2025-09-28 14:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Constant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_owner_rental_days", models.PositiveIntegerField(default=30)),
                ("min_renter_rental_hours", models.PositiveIntegerField(default=1)),
                (
                    "late_fee_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=5
                    ),
                ),
                (
                    "default_owner_share_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("80.00"), max_digits=5
                    ),
                ),
                (
                    "default_company_share_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tizim sozlamasi",
                "verbose_name_plural": "Tizim sozlamalari",
            },
        ),
    ]
